version: "3"

services:
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    ports:
      - 4194:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    container_name: cadvisor

