version: "3"

services:

  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - ./data/prometheus:/prometheus
    restart: unless-stopped
    container_name: prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
    - 3000:3000
    volumes:
    - ./data/grafana:/var/lib/grafana
    - ./grafana/provisioning:/etc/grafana/provisioning
    - ./dashboards:/dashboards
    env_file:
      - .env
    depends_on:
      - prometheus
    restart: unless-stopped
    container_name: grafana

  cadvisor:
    image: google/cadvisor:latest
    ports:
      - 4194:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: unless-stopped
    container_name: cadvisor

